"""
Pydantic models for Assembly Agent state and outputs.

Defines data structures for:
- AssembledDocument: Final document with all metadata
- AssemblyMetadata: Statistics about the assembly process
- DocumentStructure: TOC, figures, tables metadata
- QualityCheckResult: Validation results
"""

from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import datetime


class DocumentStatistics(BaseModel):
    """Statistics about the assembled document."""

    total_pages: int = Field(0, description="Total number of pages")
    total_sections: int = Field(0, description="Number of main sections")
    total_figures: int = Field(0, description="Number of figures")
    total_tables: int = Field(0, description="Number of tables")
    word_count: int = Field(0, description="Total word count")
    appendices: int = Field(0, description="Number of appendices")


class DocumentStructure(BaseModel):
    """Metadata about document structure."""

    cover_page: bool = Field(True, description="Has cover page")
    table_of_contents: bool = Field(True, description="Has TOC")
    list_of_figures: bool = Field(True, description="Has list of figures")
    list_of_tables: bool = Field(True, description="Has list of tables")
    executive_summary: bool = Field(True, description="Has executive summary")
    main_sections: int = Field(0, description="Number of main sections")
    appendices: int = Field(0, description="Number of appendices")
    version_control_page: bool = Field(True, description="Has version control page")


class QualityCheckResult(BaseModel):
    """Result of a quality validation check."""

    check_name: str = Field(..., description="Name of the check")
    passed: bool = Field(..., description="Whether check passed")
    details: str = Field("", description="Additional details or error message")


class AssemblyMetadata(BaseModel):
    """Metadata about the assembly process."""

    assembly_time_seconds: float = Field(0.0, description="Time taken to assemble document")
    llm_tokens_used: int = Field(0, description="Tokens used for LLM calls (executive summary)")
    quality_checks_passed: int = Field(0, description="Number of quality checks passed")
    quality_checks_failed: int = Field(0, description="Number of quality checks failed")
    export_formats_created: int = Field(0, description="Number of output formats created")
    timestamp: str = Field(
        default_factory=lambda: datetime.utcnow().isoformat(),
        description="Assembly completion timestamp"
    )


class AssembledDocument(BaseModel):
    """
    Final assembled HLD/SAED document.

    Contains all metadata about the complete document including file paths,
    statistics, structure, and quality validation results.
    """

    document_id: str = Field(..., description="Unique document identifier")

    # Output file paths
    formats: Dict[str, str] = Field(
        default_factory=dict,
        description="File paths for different formats (docx, pdf, html)"
    )

    # Document statistics
    statistics: DocumentStatistics = Field(
        default_factory=DocumentStatistics,
        description="Document statistics"
    )

    # Document structure metadata
    structure: DocumentStructure = Field(
        default_factory=DocumentStructure,
        description="Document structure metadata"
    )

    # Assembly process metadata
    assembly_metadata: AssemblyMetadata = Field(
        default_factory=AssemblyMetadata,
        description="Assembly process metadata"
    )

    # Quality validation results
    quality_checks: List[QualityCheckResult] = Field(
        default_factory=list,
        description="Results of quality validation checks"
    )

    # Executive summary (generated by LLM)
    executive_summary: Optional[str] = Field(
        None,
        description="Generated executive summary markdown"
    )


class FigureReference(BaseModel):
    """Reference to a figure in the document."""

    figure_number: str = Field(..., description="Assigned figure number (e.g., '5.2')")
    title: str = Field(..., description="Figure caption/title")
    section_id: str = Field(..., description="Section where figure appears")
    image_id: str = Field(..., description="Image ID from Image Generation Agent")
    page_number: Optional[int] = Field(None, description="Page number (if known)")


class TableReference(BaseModel):
    """Reference to a table in the document."""

    table_number: str = Field(..., description="Assigned table number (e.g., '3.1')")
    title: str = Field(..., description="Table caption/title")
    section_id: str = Field(..., description="Section where table appears")
    page_number: Optional[int] = Field(None, description="Page number (if known)")


class SectionReference(BaseModel):
    """Reference to a section in the document."""

    section_number: str = Field(..., description="Section number (e.g., '4.2.1')")
    title: str = Field(..., description="Section title")
    section_id: str = Field(..., description="Section ID")
    page_number: Optional[int] = Field(None, description="Page number (if known)")
    level: int = Field(1, description="Heading level (1, 2, 3)")
